### ISSUE TITLE
Color value. Instead of dec64bit - dec32bit.

### ISSUE THREAD

**Issue by patryk84a** [ysfchn/DynamicComponents-AI2#22]
It almost works fine in appinventor. Still there is a problem with 64bit values, it doesn't accept them.

However, the whole rule must be used:
What color number is yellow using the make color block?
N = B + (G + (R + (256 x opacity)) x 256) x 256

N = 0 + (255 + (255 + (256 x 255)) x 256) x 256 = 4294967040

With split color what list do we get with yellow color?
[255, 255, 0, 255]

What number is the yellow color?
4294967040 - 4294967296 = -256

Appinventor only accepts -256 ...

Only problems with this appinventor :)

**Comment by ysfchn** [comment]
Can you check again with c3b2f20877027daf6d81fec7f1a4547afc737eb0 commit?

**Comment by patryk84a** [comment]
Not all colors are correct. Instead of gray I have pink :). The previous calculations were correct. Here there is a calculation error with rgb.

**Comment by patryk84a** [comment]
White is ok -1, while gray instead of -2829100 gets -721431340

**Comment by ysfchn** [comment]
I just used the same formula as you described:

https://github.com/ysfchn/DynamicComponents-AI2/blob/c3b2f20877027daf6d81fec7f1a4547afc737eb0/TemplateCreator/TemplateCreate.py#L80-L87

**Comment by patryk84a** [comment]
I don't know what the difference is in the calculations but it works fine:

```
# TemplateCreator
# by Yusuf Cihan

import json
import ast
from flatten_json import flatten, unflatten_list
import re

def GenerateTemplate(SCM : dict):
    # Template that will be modified later.
    template = {
        # Use app name as template name.
        "name": SCM["Properties"]["AppName"],

        # Current metadata version. 
        # Needs to be 1, until a new type of metadata releases.
        "metadata-version": 1,

        # Extension version that this template generated for.
        "extension_version": 5,

        # Template author name.
        "author": "<your name>",

        # Name list of AI2 distributions name that will template work on.
        "platforms": SCM["authURL"],

        # Template parameters.
        # Will be generated automatically from SCM.
        "keys": [],

        # Components that will be created.
        # Will be generated automatically from SCM.
        "components": []
    }

    # Create a variable to store modified flatted JSON.
    flatten_json = {}

    # Edit the flatten JSON.
    for key, value in flatten(SCM["Properties"], "/").items():
        k = str(key)
        # If key ends with Uuid or Version, ignore it.
        # Because DynamicComponents-AI2 extension's JSON templates doesn't need it.
        if k.endswith("/Uuid") or k.endswith("/$Version"):
            continue
        # Else;
        else:
            # Replace the "$Components" with "components" according to the template structure.
            # $Components --> components
            k = k.replace("/$Components/", "/components/")

            # Rename the $Name and $Type according to the template structure.
            # $Name --> id
            # $Type --> type
            if k[-5:] in ["$Name", "$Type"]:
                k = k.replace("/$Name", "/id").replace("/$Type", "/type")
            # Move the properties inside a "properties" object.
            # components/Button/Text --> components/Button/properties/Text
            else:
                path = k.split("/")
                path.insert(-1, "properties")
                k = "/".join(path)

            # Check if value contains template parameter(s).
            # Parameters are defined with curly brackets.
            # {text}, {age}, {color}
            for parameter in re.findall(r'(?<=(?<!\{)\{)[^{}]*(?=\}(?!\}))', value + " " + k):
                if parameter not in template["keys"]:
                    template["keys"].append(parameter)

            # Try to convert the value automatically.
            # So if value is "True" or "False", then it will be converted to the bool and so on.
            modifiedvalue = value
            try:
                modifiedvalue = ast.literal_eval(value)
            except:
                pass

            # An exception for the color converting.
            if str(modifiedvalue).startswith("&H"):
                modifiedvalue = int(str(modifiedvalue)[2:], 16)
                modifiedvalue = modifiedvalue - 4294967296
            # Add the value and key to the modified flatten dictionary.
            flatten_json[k] = modifiedvalue

    # Now, unflat the modified flatten dictionary.
    # Save the output to the template.
    template["components"] = unflatten_list(flatten_json, "/")["$Components"]

    # Remove DynamicComponent instances from template, because it is not needed.
    for component in template["components"].copy():
        if component["type"] == "DynamicComponents":
            if component in template["components"]:
                template["components"].remove(component)

    # Return the template.
    return template
```

**Comment by patryk84a** [comment]
I think I already know:
     A = int(str(val)[0:2], 16) 
     R = int(str(val)[2:4], 16) 
     G = int(str(val)[4:6], 16) 
     B = int(str(val)[6:], 16)

**Comment by ysfchn** [comment]
The `- 4294967296` part was missing at the first commit, that's why it wasn't working at first.

I updated the code again, can you take a look to 95b2c4a9f7f2ae8c0061d89241b63445830db746 ?

**Comment by patryk84a** [comment]
Now python has stopped working and it gives errors: D. Massacre ...

**Comment by ysfchn** [comment]
You need to fetch the 0b89a93ff5ed099cd46f9d6ae0e642c25f26a815 commit also.

**Comment by patryk84a** [comment]
Still the same error with the order of the ARGB values. Erroneous color values are generated. In the SCM file, the color is A R G B and not R G B A.

**Comment by ysfchn** [comment]
I updated the code again and again at a45271bd0ed1dcf04781ebe7a74e25e5a91ff2dc

**Comment by patryk84a** [comment]
Color problem resolved.

**Comment by ysfchn** [comment]
That's nice to hear. 😄 Let me know when you encounter other issues.
